### PR TITLE
Pipe install script directly to sh

### PR DESCRIPTION
**Pull request by karlhorky**
Hi there! First of all, thanks for the Git Credential Manager, essential tool 🙌 

This pipes the install script on Linux directly to `sh`, similar to [the `flyctl` installation instructions](https://fly.io/docs/hands-on/install-flyctl/#linux)

### CODE REVIEW

**Review by ldennington — APPROVED** [review]
Thank you for working to make our docs better! This worked like a charm on my Fedora machine!

**Comment by ldennington** [comment]
For some reason, GitHub is not allowing me to enable status checks to run for you as a new contributor. I will investigate and update here when I have more information.

**Review by mjcheetham — APPROVED** [review]
Thanks for the suggestion and improvement!

**Comment by karlhorky** [comment]
Glad to help, thanks to both of you for the review + merge!

**Pull request merged**
