### PR TITLE
docs: clarify .net tool install instructions

### PR DESCRIPTION
**Pull request by CicadaCinema**
I feel the need to clarify that a .NET SDK is needed, not just a runtime.

### CODE REVIEW

**Review by ldennington — APPROVED** [review]
Looks great! Thank you for working to improve our documentation.

**Comment by ldennington** [comment]
@CicadaCinema - for some reason, GitHub is not allowing me to enable status checks to run for you as a new contributor. I will investigate and update here when I have more information.

**Comment by mjcheetham** [comment]
I'm happy to go with option 2 for the same reasons as @derrickstolee said. It's a doc change/no code, and want to make sure attribution is correct! 😄

**Comment by ldennington** [comment]
SGTM! Thanks all!

**Comment by CicadaCinema** [comment]
Thank you :)

**Pull request merged**
