### PR TITLE
updated wsl.md  to refer `git-credential-manager.exe` instead of `git-credential-manager-core.exe`

### PR DESCRIPTION
**Pull request by alex-shmyga**
updated wsl.md  to refer `git-credential-manager.exe` instead of `git-credential-manager-core.exe`

### CODE REVIEW

**Comment by dscho** [comment]
As far as I can tell, the executable name has _not_ (yet) been renamed?

**Comment by alex-shmyga** [comment]
@dscho installed today
image

**Comment by alex-shmyga** [comment]
image

**Comment by alex-shmyga** [comment]
maybe [here](https://github.com/GitCredentialManager/git-credential-manager/commit/c91294385db910f8dd15c0345e100cd034e6482f#diff-2c196fef8765d79323bebc532df759933153d72028856a28b910f4b1d96bfcd1)

**Comment by dscho** [comment]
> maybe I have an old version

Maybe? The timestamp "6/8/2019 6:14 AM" is kind of a give-away ;-) [You will want to update ASAP](https://github.com/git-for-windows/git/wiki/FAQ#should-i-upgrade-to-a-newer-git-for-windows-version).

**Comment by dscho** [comment]
In serious terms: you do _not_ have the Git Credential Manager _Core_, but Git Credential Manager _for Windows_ (which is no longer maintained).

**Comment by alex-shmyga** [comment]
> > maybe I have an old version
> 
> Maybe? The timestamp "6/8/2019 6:14 AM" is kind of a give-away ;-) [You will want to update ASAP](https://github.com/git-for-windows/git/wiki/FAQ#should-i-upgrade-to-a-newer-git-for-windows-version).

yeah, probably it's a reason xD. thanks @dscho

**Pull request closed without merging**
