### PR TITLE
Add basic support for generating code coverage reports

### PR DESCRIPTION
**Pull request by mminns**
**Problem**

I'd like to refactor parts of the Bitbucket code, but I'm uncomfortable about the level of security provided by the automated testing to avoid regressions.

I'd like to expand the testing, so I'd like to know what is currently tested or not.

**Solution**

This adds a first pass at adding basic code coverage metrics and reporting. 
They have to be run manually, they are not currently wired up to CI etc, I'd suggest doing that in a follow up.

### CODE REVIEW

**Comment by dscho** [comment]
Could this also be integrated into the CI builds?

**Comment by mminns** [comment]
Yes, I don't see why not. 

I'm not as familiar with the CI setup as I probably should be to understand where it would fit, where you would see the results etc.

I had assumed I'd do that as a follow up if the general idea was agreed.

**Review by mjcheetham — APPROVED** [review]
This looks great @mminns! Thanks for contributing this 😁

**Comment by mminns** [comment]
👍 Thanks

**Review by stranik38 — COMMENTED** [review]
- [ ]

**Pull request merged**
