### PR TITLE
use record types

### PR DESCRIPTION
**Pull request by hickford**
record types for easier debugging and unit testing

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record

### CODE REVIEW

**Review by ldennington — COMMENTED** [review]
A couple things:

1. Based on my (admittedly limited) understanding, records are best-suited for immutable data models. However, some of these classes contain mutable data. Is this the correct approach for such classes?
2. Can you add a few more details on how this makes debugging and testing easier?

**Comment by hickford** [comment]
Records automatically implement ToString (useful for debugging) and value equality (useful for unit testing). Both these properties are helpful regardless of mutability.

Immutable data is easier to reason about, so made all the record types immutable.

**Comment by mjcheetham** [comment]
Records are a C# 9 feature, which is not supported for .NET Framework (that we still target on Windows).

**Comment by hickford** [comment]
I might be wrong (unable to test), but I think this *will* build targeting .NET Framework, assuming Visual Studio 2019 or later, as records are principally a language feature rather than a library feature.

What won't work: C# 9's `init` keyword https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/init as this requires .NET 5 library [IsExternalInit](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.isexternalinit) (I tried targeting .NET Standard 2.0 and got error "IsExternalInit not defined or imported").

**Comment by mjcheetham** [comment]
I must say I'm a little hesitant to adopt _some_ of the "latest and greatest" C# features. Admittedly I'm not overtly familiar with `record [class]`s (and `record struct`s), and that drives some of it..

But, from my understanding so far, a `record [class]` provides value-type behaviour to a reference type, specifically equality. So in short you avoid passing copies but get free member-wise equality.

Of the types that you've converted from `class` to `record` I don't think we've doing any in-product tests for equality, so this is only of benefit to tests (as you call out).

A `record` also makes immutable data types easier to implement, especially when coupled with the `init` keyword on properties. Since we cannot use `init` for our Windows/.NET Framework target, I fear we'll fall in to the trap of half-adopting some language features, but not able to fully use them due to these "ah but on Windows this doesn't work" problems caught late on.

All this is to say I'm not wholly against `record`s, but I'm not sure if it's the right time to adopt them, at least until we can get to .NET 6 on Windows in a good state. Thoughts @ldennington ?

**Comment by ldennington** [comment]
I agree that the benefit does not currently outweigh the cost given our ties to .NET Framework. Let's close this for now, with the understanding we may re-visit if things change in the future.

**Pull request closed without merging**
