### PR TITLE
Update architecture.md

### PR DESCRIPTION
**Pull request by samuel-lee-msft**
Fix various typos

### CODE REVIEW

**Review by ldennington — APPROVED** [review]
Thanks for taking the time to improve our documentation! 🌟

**Review by mjcheetham — APPROVED** [review]

**Comment by Shine-1997** [comment]
#721 
#719 
#718

**Comment by Shine-1997** [comment]
@garvit-joshi

**Comment by Shine-1997** [comment]
@vdye 
#251 
#628 
@msftgits 
#424

**Pull request merged**
